apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: elasticquotas.scheduling.sigs.k8s.io
spec:
  group: scheduling.sigs.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: elasticquotas
    singular: elasticquota
    kind: ElasticQuota
    shortNames:
    - eq
    - eqs
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            min:
              type: object
            max:
              type: object
        status:
          type: object
          properties:
            used:
              type: object